#!/usr/bin/env python3
"""สร้าง DDL ของ **ตารางระบบเดิม** ที่ SGI อ่าน — จาก dump จริง `SBP/db-schema-sps_store.md`

ทำไมต้อง generate ไม่ใช่เขียนมือ
─────────────────────────────────
stub ที่เขียนมือ **เดาชื่อคอลัมน์** แล้วเทสก็ผ่านเพราะ stub มีคอลัมน์ที่โค้ดเรียกหา
รอบ 2026-09-14 พบว่าเดาผิด 4 จุดจนคิวรีของ Job 6/8/8b/12 พังทันทีถ้ารันกับฐานจริง
(`dv_code` ที่ไม่มีใน `mas_store`/`business_user` · `branch_id` ที่ไม่มีใน `fr_store` ·
 `juristic_id` ที่ไม่มีใน `mas_store`)
และผิดชนิดอีก 1 จุด (`business_user.user_id` เป็น bigint ไม่ใช่ varchar)

ผลลัพธ์ใช้กับ `SBP/srm-sps-spsap-sop-sgi-batch/test/sgi/setup-svc-db.sh`

    python3 tools/build_sgi_existing_stub_sql.py > output/sql/sgi_existing_stub.sql
"""
import io, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DUMP = ROOT / 'SBP' / 'db-schema-sps_store.md'

# ตารางของระบบเดิมที่ service ของ SGI อ่าน (ทั้งหมดเป็น read-only ตามกติกาโครงการ)
# 🔴 เพิ่ม common_code_type 2026-09-15 — seed ลงทะเบียน code type ก่อนลงค่าใน common_code
#    ถ้า stub ไม่มีตารางนี้ preflight ของ sgi_seed_data.sql จะหยุดทันทีตอนเทส
TABLES = ['mas_store', 'fr_store', 'juristic', 'mas_zone', 'common_code', 'common_code_type', 'mas_param',
          'email_template', 'email_sent', 'business_user', 'fcs_qssi_score',
          'workflow_transaction', 'workflow_history']

# 🔴 แก้ 2026-09-16 — **PK ต้องอ่านจาก dump จริง ห้าม hardcode**
#    ของเดิมเขียนว่า "ใส่เท่าที่จำเป็นให้ seed ของเทสใช้ ON CONFLICT ได้" ซึ่งทำให้ stub **โกหก**:
#      · `mas_param` ของจริง **ไม่มี PK** (มีแค่ index ธรรมดา `btree(param_name, param_value)`)
#        แต่ stub ใส่ `param_name PRIMARY KEY` → เทสเชื่อว่ากันแถวซ้ำได้ ทั้งที่ของจริงไม่กัน
#        (seed ใช้ `INSERT ... WHERE NOT EXISTS` ซึ่ง **ไม่กัน race** เมื่อ deploy พร้อมกัน)
#      · `juristic` · `mas_zone` · `business_user` ก็ถูกใส่ PK ปลอมแบบเดียวกัน
#      · กลับกัน `common_code_type` ของจริง **มี** PK `code_type` แต่ stub ไม่ได้ใส่
#    ตรวจแล้วไม่มีเทสไหนพึ่ง PK ปลอมเหล่านี้ (ON CONFLICT ใช้กับ `mas_store` ที่ของจริงมี PK อยู่แล้ว)
def read_pk(md: str, table: str) -> str | None:
    """อ่าน `- **PK:** \\`col\\`` ของตารางจาก dump — คืน None เมื่อของจริงไม่มี PK"""
    m = re.search(r'^### ' + re.escape(table) + r'$(.*?)(?=^### |\Z)', md, re.S | re.M)
    if not m:
        return None
    p = re.search(r'^- \*\*PK:\*\*\s*`([^`]+)`\s*$', m.group(1), re.M)
    return p.group(1) if p else None



def pg_type(t: str) -> str:
    t = t.strip()
    t = re.sub(r'^character varying', 'varchar', t)
    t = re.sub(r'^character\b', 'char', t)
    t = t.replace('timestamp with time zone', 'timestamptz')
    t = t.replace('timestamp without time zone', 'timestamp')
    return t


def parse(md: str) -> dict:
    out = {}
    for m in re.finditer(r'^### (\w+)\n(.*?)(?=\n### |\Z)', md, re.S | re.M):
        t = m.group(1)
        if t not in TABLES:
            continue
        cols = [(c.group(1), c.group(2).strip(), c.group(3).strip())
                for c in re.finditer(r'^\| \d+ \| `([^`]+)`[^|]*\| ([^|]+?) \| [YN] \|([^|]*)\|', m.group(2), re.M)]
        if cols:
            out[t] = cols
    return out


def main() -> int:
    if not DUMP.exists():
        print(f'ไม่พบ {DUMP}', file=sys.stderr)
        return 1
    md = io.open(DUMP, encoding='utf-8').read()
    tables = parse(md)
    missing = set(TABLES) - set(tables)
    if missing:
        print(f'ไม่พบตารางใน dump: {sorted(missing)}', file=sys.stderr)
        return 1

    print('-- generate โดย tools/build_sgi_existing_stub_sql.py — **ห้ามแก้ด้วยมือ**')
    print('-- ที่มา: SBP/db-schema-sps_store.md (dump จริงของ schema sps_store)')
    print('-- ตารางเหล่านี้เป็นของ **ระบบเดิม** SGI อ่านอย่างเดียว — สร้างที่นี่เพื่อทดสอบเท่านั้น')
    pk_of = {t: read_pk(md, t) for t in TABLES}
    print('CREATE SCHEMA IF NOT EXISTS sps_store;')
    for t in TABLES:
        print(f'\nCREATE TABLE sps_store.{t}(')
        body = []
        for name, typ, default in tables[t]:
            line = f'  {name:<34} {pg_type(typ)}'
            # คอลัมน์ที่ของจริงมี nextval(...) ต้องเป็น identity ไม่งั้น seed ของเทสต้องใส่ id เอง
            if 'nextval' in default:
                line += ' GENERATED BY DEFAULT AS IDENTITY'
            if pk_of.get(t) == name:
                line += ' PRIMARY KEY'
            body.append(line)
        print(',\n'.join(body))
        print(');')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
